"""added images for the home image

Revision ID: 2ef4926d78aa
Revises: 5a96a1eafaab
Create Date: 2024-11-15 19:31:32.575940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef4926d78aa'
down_revision = '5a96a1eafaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_one', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('image_two', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('image_three', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('image_four', sa.String(length=2000), nullable=True))
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=2000), nullable=True))
        batch_op.drop_column('image_four')
        batch_op.drop_column('image_three')
        batch_op.drop_column('image_two')
        batch_op.drop_column('image_one')

    # ### end Alembic commands ###
