"""Initial migration with updated relationships

Revision ID: 5a96a1eafaab
Revises: 
Create Date: 2024-11-12 21:33:09.955551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a96a1eafaab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('reviews')
    op.drop_table('plumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plumber',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('email', sa.VARCHAR(length=1200), nullable=False),
    sa.Column('number', sa.VARCHAR(length=1200), nullable=True),
    sa.Column('password', sa.VARCHAR(length=1200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('review', sa.TEXT(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('image', sa.VARCHAR(length=2550), nullable=True),
    sa.Column('location', sa.VARCHAR(length=2550), nullable=False),
    sa.Column('plumber_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['plumber_id'], ['plumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
