"""added heading column to HomePage table

Revision ID: 7871f9664fd9
Revises: 2ef4926d78aa
Create Date: 2024-11-17 14:18:36.801726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7871f9664fd9'
down_revision = '2ef4926d78aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HomePageContent')
    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heading', sa.String(length=2000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.drop_column('heading')

    op.create_table('HomePageContent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('heading', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('subheading', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
