"""Added 2 more heading and subheading columns to the homePage table

Revision ID: 905179964a36
Revises: 
Create Date: 2024-12-19 21:54:48.566800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905179964a36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heading_two', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('subheading_two', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('description_two', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('heading_three', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('subheading_three', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('description_three', sa.String(length=2000), nullable=True))

    with op.batch_alter_table('Jobs_Done', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=2550), nullable=True))
        batch_op.add_column(sa.Column('service_provider_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['service_provider_id'], ['id'])
        batch_op.drop_column('main_image_path')
        batch_op.drop_column('image_two_path')
        batch_op.drop_column('User_id')
        batch_op.drop_column('image_one_path')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Jobs_Done', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('image_one_path', sa.VARCHAR(length=2000), nullable=True))
        batch_op.add_column(sa.Column('User_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('image_two_path', sa.VARCHAR(length=2000), nullable=True))
        batch_op.add_column(sa.Column('main_image_path', sa.VARCHAR(length=2000), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['User_id'], ['id'])
        batch_op.drop_column('service_provider_id')
        batch_op.drop_column('image')

    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.drop_column('description_three')
        batch_op.drop_column('subheading_three')
        batch_op.drop_column('heading_three')
        batch_op.drop_column('description_two')
        batch_op.drop_column('subheading_two')
        batch_op.drop_column('heading_two')

    # ### end Alembic commands ###
