"""added columns from the pull request

Revision ID: c8dbf89753c9
Revises: 
Create Date: 2024-12-25 02:39:18.585377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dbf89753c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserDetails')
    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heading_two', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('subheading_two', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('description_two', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('heading_three', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('subheading_three', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('description_three', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HomePage', schema=None) as batch_op:
        batch_op.drop_column('description_three')
        batch_op.drop_column('subheading_three')
        batch_op.drop_column('heading_three')
        batch_op.drop_column('description_two')
        batch_op.drop_column('subheading_two')
        batch_op.drop_column('heading_two')

    op.create_table('UserDetails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('password', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('about', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('facebook_url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('instagram_url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('hackerrank_url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('role', sa.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
