"""removed portfolio tables from db

Revision ID: cca64722f349
Revises: 
Create Date: 2024-12-05 00:20:35.750468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca64722f349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accreditation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2000), nullable=False),
    sa.Column('image', sa.String(length=2000), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Skills')
    op.drop_table('accreditation')
    op.drop_table('Projects')
    op.drop_table('Experience')
    op.drop_table('Education')
    op.drop_table('Languages')
    with op.batch_alter_table('CompanyDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=2000), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CompanyDetails', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    op.create_table('Languages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Education',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=500), nullable=False),
    sa.Column('institution', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('qualification', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Experience',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.VARCHAR(length=5000), nullable=False),
    sa.Column('role', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('company', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('location', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thumbnail', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('title', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('description', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('repo_link', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('demo_link', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accreditation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('image', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('description', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Accreditation')
    # ### end Alembic commands ###
